import { ScrollViewStyleReset } from 'expo-router/html';
import { type PropsWithChildren } from 'react';

import { Colors } from '@/constants/theme';
import { OG_IMAGE, SITE_DESCRIPTION, SITE_NAME, SITE_TITLE, absoluteUrl } from '@/constants/site';

/**
 * The HTML around the app on the web — head tags a crawler reads before any
 * JavaScript runs.
 *
 * ⚠ This file runs in Node during `expo export`, once per pre-rendered route,
 *   and never in the browser. No hooks, no `window`, no global CSS import
 *   (that belongs in the root layout) — and nothing here can depend on which
 *   route is being rendered, because every route gets the same shell.
 *
 * ⚠ The title and the description are deliberately NOT here.
 *
 *   `expo-router/head` renders them, and it renders them into this same head
 *   from the root layout. Declaring a `<title>` in both places emits two, and
 *   the one a scraper reads is whichever it meets first — which is how a page
 *   ends up advertising a title nobody in the repo wrote. Everything below is
 *   the half that never varies: the icons and the share card.
 *
 * Replacing the default shell means the two lines Expo used to supply are now
 * ours to keep: the viewport meta, without which every phone renders the page
 * at 980px and scales it down, and `ScrollViewStyleReset`, without which a
 * `ScrollView` grows the document instead of scrolling inside its own box.
 */
export default function Root({ children }: PropsWithChildren) {
  const image = absoluteUrl(OG_IMAGE.path);

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        {/*
          The icons.

          `favicon.ico` is generated by Expo from `web.favicon` in app.json and
          dropped at the root of dist; the two below are ours, copied verbatim
          out of `public/`. The apple-touch-icon is what iOS uses when somebody
          adds the site to their home screen — without it Safari screenshots
          the page and uses that, which looks exactly as bad as it sounds.
        */}
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180" />
        <meta name="theme-color" content={Colors.light.primary} />
        <meta name="application-name" content={SITE_NAME} />
        <meta name="apple-mobile-web-app-title" content={SITE_NAME} />

        {/*
          The share card.

          Open Graph is read by WhatsApp, Facebook, LinkedIn, Slack and iMessage;
          Twitter/X reads its own `twitter:` tags and falls back to OG for the
          rest. Both are listed because `summary_large_image` is the difference
          between the card above and a thumbnail the size of a postage stamp.

          `og:title` and `og:description` are repeated from the copy the root
          layout puts in `<title>`: a scraper reads these tags, not the title
          element, and several of them will not fall back to it.
        */}
        <meta property="og:site_name" content={SITE_NAME} />
        <meta property="og:type" content="website" />
        <meta property="og:title" content={SITE_TITLE} />
        <meta property="og:description" content={SITE_DESCRIPTION} />
        <meta property="og:image" content={image} />
        <meta property="og:image:width" content={String(OG_IMAGE.width)} />
        <meta property="og:image:height" content={String(OG_IMAGE.height)} />
        <meta property="og:image:alt" content={OG_IMAGE.alt} />
        <meta property="og:url" content={absoluteUrl('/')} />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={SITE_TITLE} />
        <meta name="twitter:description" content={SITE_DESCRIPTION} />
        <meta name="twitter:image" content={image} />
        <meta name="twitter:image:alt" content={OG_IMAGE.alt} />

        <ScrollViewStyleReset />
      </head>
      <body>{children}</body>
    </html>
  );
}
